### ISSUE TITLE
no_devices

### ISSUE THREAD

**Issue by danieldobosi** [guillaumeseur/hafele_connect_mesh#1]
Hello there,

1. Complete fresh HomeAssistant installation
2. Fresh HACS integration
3. Häfele system is working on the local LAN, I can toggle the LED lights
4. Successfully added Häfele mesh connect integration

When trying to add the Häfele device, I'm getting this error message:
![screenshot](https://github.com/user-attachments/assets/a4af65e2-34a6-4b6c-b5e0-fca327266ab4)

Any ide what this is and how can I avoid it?

Kind Regards,
Daniel

**Comment by guillaumeseur** [comment]
I have an idea what it might be, but just take in mind that this integration needs an update.
Still have some work to do as I don't get the results I want.

But your ptoblem might have to do that Hafele did change the linking to the cloud:
open up the 'Connect Mesh' app
Home > Settings > Gateway > Cloud settings > Synced networks > ...
There should be an upload button (left from the delete button).
Now retry adding this integration and it might work again.

**Comment by danieldobosi** [comment]
Hi, appreciate the answer, let me try this :)

**Comment by danieldobosi** [comment]
Hm, so you were right, the network was not synched at first.
Now what I did was completely reset everything, even the GW and re-created the network.
Network is synched now, after that I've re-created the API key but still getting the same error message. Any more ideas?

**Comment by danieldobosi** [comment]
EDIT: it's working! Needed to re-upload the network again. Thanks again! :)

**Comment by guillaumeseur** [comment]
I was literally about to send this message, but see that it works now! For others who might encounter the error, here's a bit more information on where to look:

Can you go to this website [https://webapi.cloud.connect-mesh.io/api](https://webapi.cloud.connect-mesh.io/api) and do the following:

1. **Authorize** > bearer value: > fill in your API token (CMC_.......) > authorize
2. Expand the **'GET /networks'** section > click **Try it out** > click on **Execute**
3. The server response should be **'code 200'** with the network ID, name, etc., shown in the body.

If you don't get the **'code 200'**, there might be something wrong with the API. If you do get it, then it's likely an issue with the integration.

I already have the next version ready. Just need some more testing and finishing touches. I'll probably release it later this week or early next week.

**Comment by guillaumeseur** [comment]
Also, better save the API key for now, you might need it for the next version, as it's completely recoded.

**Comment by tOsaer** [comment]
> I was literally about to send this message, but see that it works now! For others who might encounter the error, here's a bit more information on where to look:
> 
> Can you go to this website https://webapi.cloud.connect-mesh.io/api and do the following:
> 
> 1. **Authorize** > bearer value: > fill in your API token (CMC_.......) > authorize
> 2. Expand the **'GET /networks'** section > click **Try it out** > click on **Execute**
> 3. The server response should be **'code 200'** with the network ID, name, etc., shown in the body.
> 
> If you don't get the **'code 200'**, there might be something wrong with the API. If you do get it, then it's likely an issue with the integration.
> 
> I already have the next version ready. Just need some more testing and finishing touches. I'll probably release it later this week or early next week.


I'm not getting the "code 200" for the server response, what could be the issue?

**Comment by LooxFoox** [comment]
The API is currently down for maintenance. There is a big update of the app scheduled for later this week, so i suggest you wait until the version 2.2 is out, then try again

**Comment by lukeh1101-dev** [comment]
@LooxFoox Any update on the App or API? It seemed to have been back last week then down again?

**Comment by LooxFoox** [comment]
New App version has been submitted to the app stores yesterday evening. 

Details on the new version are listed here: [Version 2.2](https://help.connect-mesh.io/versions/2025/02/15/app-update-2-2-0)

The API should be up and running again smoothly now, details and more information about the APIs (both RestAPI and MQTT) here:
[Documentation Mesh2X](https://help.connect-mesh.io/docs/professional/information)

**Comment by lukeh1101-dev** [comment]
I’m still struggling, my API doesn’t seem to work still and the developer sections throws me a 500 error. I’ll leave it a couple of days but it’s disappointing from a supplier POV that it puts a cloud over the reliability of the Hafele mesh system for anyone wanting to use its product at a more professional level at its relatively high price point

**Comment by tOsaer** [comment]
The webAPI seems to work, but the integration is still having troubles:


```
2025-09-12 10:27:52.789 DEBUG (MainThread) [custom_components.hafele_connect_mesh.light] Finished fetching light data in 0.076 seconds (success: True)
2025-09-12 10:27:52.789 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/hafele_connect_mesh/light.py", line 86, in _handle_coordinator_update
    self._update_attributes()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/hafele_connect_mesh/light.py", line 161, in _update_attributes
    state = self.coordinator.data.get(self._attr_unique_id, {}).get("state", {})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
